name = "DCorbinJLReg"
uuid = "5ff70fa9-e567-47c0-a843-2243d757a045"
repo = "https://github.com/dfcorbin/DCorbinJLReg.jl.git"
description = "Registry for my in-development packages."

[packages]
d57b171a-2237-49d2-a8f0-cd22f4c2e2bf = { name = "RecursivePartition", path = "RecursivePartition" }

